import Head from "next/head";
import { Footer } from "../components/Footer";
import { HeroSections } from "./herosections";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Marcelo |Slider Image</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSections />
      <Footer />
    </div>
  );
}
